### ISSUE TITLE
log4j-detector-2021.12.12.jar does not traverse symbolic links

### ISSUE THREAD

**Issue by chrstnrnngr** [mergebase/log4j-detector#1]
![2021-12-13_log4j-detector_symlinks](https://user-images.githubusercontent.com/96044579/145772931-b642d66d-c7e6-4405-a2e4-8938a66211f1.png)

**Comment by juliusmusseau** [comment]
Thanks for the bug report!

**Comment by juliusmusseau** [comment]
It traverses symlinks now.
