### ISSUE TITLE
Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by stephanenovakoviclmdt** [mergebase/log4j-detector#16]
I try to use the command line but I get an Error
Error: Invalid or corrupt jarfile log4j-detector-2021.12.14.jar

**Comment by UraniumDonut** [comment]
Same error FreeBSD 12.0

**Comment by MoritzSalein** [comment]
I get the same problem when I copy the file with wget or curl in a shell. For me it only works with a download via the Firefox browser.

**Comment by LinuxETC** [comment]
Question to those posting here:
Was this file retrieved via `git`, `wget`, `curl`, or via a web browser?

**Comment by stephanenovakoviclmdt** [comment]
I tried wget on my Ubuntu server. It gave me the error.
I had the same issue when I downloaded the file with Google Chrome on WIndows then sent it to my server through WinSCP.

**Comment by LinuxETC** [comment]
@stephanenovakoviclmdt 
Did you try using `git clone <this repo>` out of curiosity, and receive similar issues?

**Comment by stephanenovakoviclmdt** [comment]
@LinuxETC no, I don't see why I should. I just want to get the file. Why wget doesn't work ?

**Comment by LinuxETC** [comment]
Just an idea since using `git` for Github make reasonable sense where other means on the CLI have failed.

**Comment by stephanenovakoviclmdt** [comment]
@LinuxETC I don't know how git clone works.

**Comment by LinuxETC** [comment]
@stephanenovakoviclmdt 
From the CLI, for this specific repo use 
```
git clone https://github.com/mergebase/log4j-detector.git
```
which will clone the existing Github repo in full to your system.  This is assuming you have `git` installed already on your system as well.

**Comment by LinuxETC** [comment]
@stephanenovakoviclmdt 
Good to hear! 
May I suggest closing out this Issue so the repo's owners can focus on other issues then? ;-)
Thanks in advance.

**Comment by juliusmusseau** [comment]
Thanks everyone for helping out @stephanenovakoviclmdt !

p.s.  My favourite "git pull" approach is:   "git pull -r --autostash".   Here's why:  https://mergebase.com/blog/doing-git-wrong/
