### ISSUE TITLE
Justification for patterns

### ISSUE THREAD

**Issue by dminuoso** [mergebase/log4j-detector#18]
Hi.

I was wondering, is there a particular reason you look for say `core/LogEvent.class` rather than `log4j/com/LogEvent.class`?

https://github.com/mergebase/log4j-detector/blob/master/src/main/java/com/mergebase/log4j/Log4JDetector.java#L21-L26

**Comment by juliusmusseau** [comment]
The log4j-core artifact typically contains LogEvent.class inside a "core" sub-directory.  

Try downloading [log4j-core-2.16.0.jar](https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar) for yourself to see.  Rename it to *.zip and then explore its contents.  You should see a "LogEvent.class" file inside there inside the ".\org\apache\logging\log4j\core" sub-directories.
