### ISSUE TITLE
Does log4j 2.12.2 even exist?

### ISSUE THREAD

**Issue by PeerHartmann** [mergebase/log4j-detector#19]
In the readme it says that version 2.12.2 is considered safe. I wonder how this can be true as only version >=2.15 are considered safe. Also the version 2.12.2 does not exist at apache. Is this a typo? Or what was the intention.

Thanks for your efforts!

**Comment by juliusmusseau** [comment]
Currently the tag "log4j-2.12.2-rc1" exists in the [log4j git repository](https://github.com/apache/logging-log4j2), and a vote is underway on the developer mailing list to release it, after which point it will become the official 2.12.2 release (assuming the vote passes - looks like it will based on the emails on the log4j mailing list so far).

**Comment by PeerHartmann** [comment]
Thanks for the quick reply. I will have a look at it.

**Comment by juliusmusseau** [comment]
It's officially released now (and published to maven central): https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.12.2/
