### ISSUE TITLE
Problem: cannot read - XXX

### ISSUE THREAD

**Issue by Timokirch** [mergebase/log4j-detector#25]
Hi all, thanks for that fantastic tool! Short question with the newly released version of today (15th of december). I do see a lot of read errors. Do i need to run this as sudo? 

![image](https://user-images.githubusercontent.com/59065878/146156919-7dacca33-4b99-43e0-a104-030c40445a41.png)

**Comment by jsark78** [comment]
/proc is a special file system, it will not contain Java code. No amount of privileges will let you scan certain things in there. You may want to not include /proc in your scanning runs.

**Comment by johanhammar** [comment]
We also have this problem but for other files i.e.

`-- Problem: cannot read - /opt/<redacted>`

**Comment by daswars** [comment]
We to, how we can hide "--Problem:" messages
i make a scan to "/opt /home /var /usr"
```
-- Problem: cannot read - /run/udev/watch/1
-- Problem: cannot read - /run/udev/watch/10
-- Problem: cannot read - /run/udev/watch/11
-- Problem: cannot read - /run/udev/watch/14
-- Problem: cannot read - /run/udev/watch/16
-- Problem: cannot read - /run/udev/watch/17
-- Problem: cannot read - /run/udev/watch/18
-- Problem: cannot read - /run/udev/watch/19
-- Problem: cannot read - /run/udev/watch/2
-- Problem: cannot read - /run/udev/watch/20
-- Problem: cannot read - /run/udev/watch/21
-- Problem: cannot read - /usr/bin/pcp2csv
-- Problem: cannot read - /usr/lib/debug/usr/.dwz
-- Problem: cannot read - /usr/lib/modules/3.10.0-1062.1.1.el7.x86_64/build
-- Problem: cannot read - /usr/lib/modules/3.10.0-1062.1.1.el7.x86_64/source
-- Problem: cannot read - /usr/lib/modules/3.10.0-1062.12.1.el7.x86_64/build
-- Problem: cannot read - /usr/lib/modules/3.10.0-1062.12.1.el7.x86_64/source
-- Problem: cannot read - /usr/lib/modules/3.10.0-1127.19.1.el7.x86_64/build
-- Problem: cannot read - /usr/lib/modules/3.10.0-1127.19.1.el7.x86_64/source
-- Problem: cannot read - /usr/lib/modules/3.10.0-1160.25.1.el7.x86_64/build
-- Problem: cannot read - /usr/lib/modules/3.10.0-1160.25.1.el7.x86_64/source
-- Problem: cannot read - /usr/lib/modules/3.10.0-1160.42.2.el7.x86_64/build
-- Problem: cannot read - /usr/lib/modules/3.10.0-1160.42.2.el7.x86_64/source
-- Problem: cannot read - /usr/libexec/pcp/bin/pcp-lvmcache
-- Problem: cannot read - /usr/share/cockpit/branding/debian/favicon.ico
-- Problem: cannot read - /usr/share/cockpit/branding/debian/logo.png
-- Problem: cannot read - /usr/share/cockpit/branding/ubuntu/logo.png
-- Problem: cannot read - /usr/share/doc/jing-20091111/doc/api
-- Problem: cannot read - /usr/share/PackageKit/icons
```

It is better if the problem message is only displayed in verbose mode.

**Comment by juliusmusseau** [comment]
v2021.12.16 will be much better in this regard since it only complains about files it cannot read IF they are the type of file it wants to read (e.g., *.zip, *.jar, *.war).

**Comment by jsark78** [comment]
Do you have file system permissions to read these files?

> It is better if the problem message is only displayed in verbose mode.

I respectfully disagree. Hiding problems behind a verbose flag leads to a false sense of security. Would you truly want to trust a checking tool which may fail to check some files, and silently ignores them, telling you everything is okay?
