### ISSUE TITLE
_POTENTIALLY_SAFE_ :-| (or did you already remove JndiLookup.class?) 

### ISSUE THREAD

**Issue by venneq** [mergebase/log4j-detector#26]
Result of a scanned file: **__POTENTIALLY_SAFE__ :-| (or did you already remove JndiLookup.class?)** 
Good thing you thought about this case but...
If the answer is _Yes_, would this resolve to a __SAFE__ state? This is unclear. Please add this info to the result text / question.

Edit: grammar

**Comment by juliusmusseau** [comment]
That result always means "JndiLookup.class" is not present.  And so, yes, I think it means that version of Log4J is SAFE.  

Just be careful to make sure it was someone from your team/company that removed JndiLookup.class and not attackers trying to claim your servers for themselves (to block other attackers)!

**Comment by venneq** [comment]
Thanks for your answer and clarifying. And good input on the „who deleted the file“ question. Didn’t even think about that.
My concern was that you could include the conclusion „Yes = SAFE“ in the logfile for clarification. After your answer a better addition would be „Yes = SAFE if you or someone from your company removed it. Attackers might remove it to keep control“.

**Comment by juliusmusseau** [comment]
Added info about this to README.md.
