### ISSUE TITLE
Add explanation of _OLD_ in README.md

### ISSUE THREAD

**Issue by Nitschi** [mergebase/log4j-detector#27]
Hello,

A bunch of my programs give results such as 
```
C:\Users\username\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\201.7223.86\lib\log4j.jar contains Log4J-1.x   <= 1.2.17 _OLD_ :-|
```

I found [this issue](https://github.com/mergebase/log4j-detector/issues/4#issuecomment-994482216), but it's not yet documented.

Thank you for the helpful tool!
Alex

**Comment by juliusmusseau** [comment]
Done!  (Documented now!)
