### ISSUE TITLE
21.12.15 Problem: cannot read

### ISSUE THREAD

**Issue by Bysoultear** [mergebase/log4j-detector#30]
21.12.15 the Log explode
A lot of "-- Problem: cannot read" messages
and not just jar,war, zip  etc.  ... its evry file like mp4,png,exe,dll,xml ....

**Comment by juliusmusseau** [comment]
That means the current user on the machine running the scan lacks permission to read those files.

**Comment by Bysoultear** [comment]
1. User = Administrator
2. why it scan evrything and not just jar,war, zip etc?
3. <21.12.15 this didnt happen

**Comment by juliusmusseau** [comment]
Fixed in v2021.12.16.  Now it checks if file-type is interesting before it attempts to read it. Also, now the "-- Problem:" messages are always sent to STDERR.
