### ISSUE TITLE
-- Problem - java.io.EOFException: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by linlo68** [mergebase/log4j-detector#32]
Getting this on a bunch of files. Is this expected behavior?

**Comment by thorag76** [comment]
I'm getting this, too, it seems to be related to corrupt nested JAR files.
Redhat products of certain versions seem to be affected preferredly.
Found 906 of 900 lines resulting in an EOFException for a .eclipse/org.eclipse.platform_4.17.0_... folder in my home directory.

**Comment by juliusmusseau** [comment]
Fixed in latest version (v2021.12.16).  Was a problem in my code (the nested jars were fine).
