### ISSUE TITLE
Mount points

### ISSUE THREAD

**Issue by f0rk-b0mb** [mergebase/log4j-detector#40]
Hi @ ALL

I have a Problem with mount points. I don't want to search in mount points. Is it possible to exclude them?

greetings

**Comment by beckerr-rzht** [comment]
I had the same problem. Here I describe a solution that uses `find` and the `--stdin` option I added: https://github.com/mergebase/log4j-detector/issues/42#issuecomment-996802447

**Comment by juergenhoetzel** [comment]
> Hi @ ALL
> 
> I have a Problem with mount points. I don't want to search in mount points. Is it possible to exclude them?
> 
> greetings

I have written a `log4j2`detector in `GOLANG` which has a `-samefs`flag: https://github.com/juergenhoetzel/log4j2go

**Comment by juliusmusseau** [comment]
v2021.12.20 supports --stdin and --exclude=X options.
