### ISSUE TITLE
Error: Invalid or corrupt jarfile log4j-detector-2021.12.16.jar

### ISSUE THREAD

**Issue by linlo68** [mergebase/log4j-detector#41]
Unable to run the new version. Is anyone else having this issue?

I get the following when trying to execute the jar:

Error: Invalid or corrupt jarfile log4j-detector-2021.12.16.jar

**Comment by juliusmusseau** [comment]
Be sure to click on the little "[ Download ]" button after clicking on the "log4j-detector-2021.12.16.jar" link from the first page!

The correct URL for downloading is this:

https://github.com/mergebase/log4j-detector/raw/master/log4j-detector-2021.12.16.jar

**Comment by linlo68** [comment]
That was the issue! Thank you... all is working now.
