### ISSUE TITLE
json format output The Results

### ISSUE THREAD

**Issue by zhurkin** [mergebase/log4j-detector#46]
json is a really universal format that is convenient and easy to parse. It would be nice to add support for report output in this format.

**Comment by juliusmusseau** [comment]
Bad news:  I don't want to add any dependencies.

Good news: I happen to have written my own JSON parser/formatter...  https://github.com/mergebase/java2json   ;-)

Yes, I'll do this!

(and who among us has not written their own JSON parser, right???)

**Comment by zhurkin** [comment]
> (and who among us has not written their own JSON parser, right???)

Good !

**Comment by juliusmusseau** [comment]
implemented this in v2021.12.20
