### ISSUE TITLE
return error codes

### ISSUE THREAD

**Issue by eingemaischt** [mergebase/log4j-detector#5]
Could you return an error count if you find a vulnerability?

For example 1 for warnings (e.g. if a version 1 was found) and 2 for a vulnerable log4j2 would be great to directly include it as icinga/nagios-Check ;-)

(BTW: Thank you for your great work!)

**Comment by juliusmusseau** [comment]
Done !  Great idea !

p.s.  Thanks for your kind words - very appreciated.

(Note:  we currently don't detect Log4J 1.2.x, but plan to add that tomorrow).
