### ISSUE TITLE
Scan `.jpi` and `.hpi` filetypes

### ISSUE THREAD

**Issue by rgmz** [mergebase/log4j-detector#54]
[Jenkins and Hudson plugins are written in Java but packaged as `.jpi` or `.hpi` files instead of jar/ear/war.](https://stackoverflow.com/a/30680083)

We have found plugins with a vulnerable version of log4j-core, like [the Checkmarx plugin < 2021.4.3](https://plugins.jenkins.io/checkmarx/#releases).

I will open a PR for this.

**Comment by juliusmusseau** [comment]
Fixed in v2021.12.20 !
