### ISSUE TITLE
Detection of Log4j 1.x as vulnerable

### ISSUE THREAD

**Issue by dnjoe96** [mergebase/log4j-detector#67]
According to the https://logging.apache.org/log4j/2.x/security.html  "**Log4j 1.x is not impacted by this vulnerability.**".  And currently the scanner detects this version as vulnerable, and collaborated by the README which states "Currently reports log4j-core versions 2.3.1, 2.12.3, and 2.17.0 as _SAFE_, 2.12.2, 2.15.0 and 2.16.0 as _OKAY_ and **all other versions as _VULNERABLE_**"

**Comment by rgmz** [comment]
@dnjoe96 Can you share some output where log4j 1.x is detected as VULNERABLE? [I've only seen it marked as "OLD".](https://github.com/mergebase/log4j-detector#understanding-the-results-)

**Comment by juliusmusseau** [comment]
I've updated the README.md to try and make this a little clearer:

> Currently reports log4j-core versions 2.3.1, 2.12.3, and 2.17.0 as _SAFE_, 2.12.2, 2.15.0 and 2.16.0 as _OKAY_ and all other versions as _VULNERABLE_ (although it does report pre-2.0-beta9 as _POTENTIALLY_SAFE_). It reports older log4j-1.x versions as _OLD_.

(Technically, "log4j-core" was never released as a 1.x, because back then the artifact name was "log4j/log4j", and it was renamed to "log4j-core" starting with version 2.0, but that level of technical pedantry about log4j component names probably not helpful to most people.)

**Comment by rgmz** [comment]
> (Technically, "log4j-core" was never released as a 1.x, because back then the artifact name was "log4j/log4j", and it was renamed to "log4j-core" starting with version 2.0, but that level of technical pedantry about the history of log4j component names probably not helpful to most people.)

It's a common source of confusion that 1.x was literally called `log4j` but 2.x was released under a different groupId (`org.apache.logging.log4j`) and split into different modules.

**Comment by dnjoe96** [comment]
> @dnjoe96 Can you share some output where log4j 1.x is detected as VULNERABLE? [I've only seen it marked as "OLD".](https://github.com/mergebase/log4j-detector#understanding-the-results-)

Okay, seeing as the READme has been updated. It is satisfactory now. I will ask that my customer to refer to the updated readme that had dem cringy. 

I'm sorry, I did not get this output. I merely confirmed the customer's concerns with the readme of the application. Thanks you.

**Comment by dnjoe96** [comment]
> 

Thank you for this. Great work!
