### ISSUE TITLE
Scan .car files

### ISSUE THREAD

**Issue by rgmz** [mergebase/log4j-detector#72]
This is a format I've never encountered before. The "Carbon Application Archive" format seems to be used for [Apache Synapse](https://synapse.apache.org/) and WSO2.

More research is required to determine if this is a "deployable" archive like .jar or the others.

References:
- https://github.com/devmix/maven-car-plugin
- https://docs.wso2.com/display/DVS370/Deploying+a+CAR+File+with+the+Maven+Plug-In
- https://github.com/censof-obb/Eclaim-lpnm-Integration/blob/f9e6205f818043625bc600bdcb4c1844b0892bcd/EclaimIntegrationApp/target/EclaimIntegrationApp_1.0.0.car

**Comment by juliusmusseau** [comment]
v2021.12.29 released which addresses this (all files that match *.*ar will be scanned now).
